### ISSUE TITLE
TypeError: Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by ittayd** [obogo/ux-angularjs-datagrid#83]
Check https://jsfiddle.net/nwx6vgrm/2/. The use of ng-if causes:
```
TypeError: Cannot read property 'insertBefore' of null
    at forEach.after (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:3453:13)
    at Object.JQLite.(anonymous function) [as after] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:3537:17)
    at domInsert (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:5050:35)
    at Object.enter (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:5213:9)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:24071:26
    at publicLinkFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:7554:29)
    at boundTranscludeFn (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:7699:16)
    at controllersBoundTransclude (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:8316:18)
    at Object.ngIfWatchAction [as fn] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:24062:15)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js:15826:29)
```

**Comment by wesjones** [comment]
You cannot use ng-if on the main node of a row. That needs to be there for the datagrid to manage. You can hide child elements of a row with ng-if.
